#
# Cookbook Name:: dev
# Recipe:: vim
#
# Copyright (c) 2015 The Authors, All Rights Reserved.

header = "\" Generated by Chef. DO NOT EDIT!"

template "#{node.home}/.vimrc" do
  owner node.current_user
  group node.current_user
  mode '0600'
  source 'vimrc.erb'
  variables({
    :header => header
  })
end

["#{node.home}/.vim", "#{node.home}/.vim/autoload", "#{node.home}/.vim/bundle", "#{node.home}/.vim/plugin"].each do |path|
  directory path do
    owner node.current_user
    group node.current_user
    mode '0700'
  end
end

remote_file "#{node.home}/.vim/autoload/pathogen.vim" do
  owner node.current_user
  group node.current_user
  mode '0600'
  source 'https://github.com/tpope/vim-pathogen/raw/master/autoload/pathogen.vim'
end

git "#{node.home}/.vim/bundle/vim-go" do
  repository "https://github.com/fatih/vim-go.git"
  action :export
end

remote_file "#{node.home}/.vim/plugin/DoxygenToolkit.vim" do
  owner node.current_user
  group node.current_user
  mode '0600'
  source 'http://www.vim.org/scripts/download_script.php?src_id=14064'
end

remote_file "#{node.home}/.vim/plugin/fugitive.vim" do
  owner node.current_user
  group node.current_user
  mode '0600'
  source 'https://github.com/tpope/vim-fugitive/raw/master/plugin/fugitive.vim'
end

remote_file "#{node.home}/.vim/plugin/gcov.vim" do
  owner node.current_user
  group node.current_user
  mode '0600'
  source 'http://www.vim.org/scripts/download_script.php?src_id=8141'
end

remote_file "#{node.home}/.vim/plugin/cscope_maps.vim" do
  owner node.current_user
  group node.current_user
  mode '0600'
  source 'http://cscope.sourceforge.net/cscope_maps.vim'
end

template "#{node.home}/.vim/plugin/cscope_db.vim" do
  owner node.current_user
  group node.current_user
  mode '0600'
  source 'cscope_db.vim.erb'
  variables({
    :header => header
  })
end
