#
# Cookbook Name:: dev
# Recipe:: vim
#
# Copyright (c) 2015 The Authors, All Rights Reserved.

header = "\" Generated by Chef. DO NOT EDIT!"

home = node['etc']['passwd'][node[:user]]['dir']

template "#{home}/.vimrc" do
  owner node[:user]
  group node[:user]
  mode '0600'
  source 'vimrc.erb'
  variables({
    :header => header
  })
end

["#{home}/.vim", "#{home}/.vim/autoload", "#{home}/.vim/bundle", "#{home}/.vim/plugin"].each do |path|
  directory path do
    owner node[:user]
    group node[:user]
    mode '0700'
  end
end

remote_file "#{home}/.vim/autoload/pathogen.vim" do
  owner node[:user]
  group node[:user]
  mode '0600'
  source 'https://github.com/tpope/vim-pathogen/raw/master/autoload/pathogen.vim'
end

git "#{home}/.vim/bundle/vim-go" do
  repository "https://github.com/fatih/vim-go.git"
  action :export
end

remote_file "#{home}/.vim/plugin/DoxygenToolkit.vim" do
  owner node[:user]
  group node[:user]
  mode '0600'
  source 'http://www.vim.org/scripts/download_script.php?src_id=14064'
end

remote_file "#{home}/.vim/plugin/fugitive.vim" do
  owner node[:user]
  group node[:user]
  mode '0600'
  source 'https://github.com/tpope/vim-fugitive/raw/master/plugin/fugitive.vim'
end

remote_file "#{home}/.vim/plugin/gcov.vim" do
  owner node[:user]
  group node[:user]
  mode '0600'
  source 'http://www.vim.org/scripts/download_script.php?src_id=8141'
end
